const tablesSchema = [
  {
    id: '5c3c67a95ec82cdea85b2bff',
    name: 'Users',
    displayName: 'Users',
    isSystem: true,
    fields: [
      {
        id: '5c3c67a95ec82c06115b2c00',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67a95ec82c0fb35b2c01',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67a95ec82c32235b2c03',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67a95ec82c4a4c5b2c07',
        name: 'email',
        displayName: 'Email',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 191,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67a95ec82c63a35b2c0b',
        name: 'firstName',
        displayName: 'First Name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67a95ec82c73775b2c0d',
        name: 'lastName',
        displayName: 'Last Name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67a95ec82c255e5b2c0f',
        name: 'cellPhone',
        displayName: 'Cell Phone',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67a95ec82c853f5b2c11',
        name: 'workPhone',
        displayName: 'Work Phone',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67a95ec82cc6795b2c13',
        name: 'workPhoneExt',
        displayName: 'Work Phone Ext',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67a95ec82c855d5b2c15',
        name: 'gender',
        displayName: 'Gender',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67a95ec82c84285b2c17',
        name: 'birthday',
        displayName: 'Birthday',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67a95ec82c4f575b2c19',
        name: 'language',
        displayName: 'Language',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67a95ec82ce9f15b2c1b',
        name: 'timezone',
        displayName: 'Timezone',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cb6535b2cd5',
        name: 'sentInvitations',
        displayName: 'Sent Invitations',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: {
          refFieldName: 'invitedBy',
          refFieldDisplayName: 'Invited By',
          relationTableName: 'InvitationInvitedBy',
          relationFieldName: 'bid',
          refTable: {
            id: '5c3c67aa5ec82cdc315b2c88',
            name: 'Invitations',
            __typename: 'Table',
          },
          refFieldIsList: false,
          refFieldIsRequired: true,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c27b05b2cd7',
        name: 'roles',
        displayName: 'Roles',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: {
          refFieldName: 'users',
          refFieldDisplayName: 'User',
          relationTableName: 'UsersRoles',
          relationFieldName: 'aid',
          refTable: {
            id: '5c3c67aa5ec82c2df45b2c76',
            name: 'Roles',
            __typename: 'Table',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c426b5b2ce3',
        name: 'avatar',
        displayName: 'Avatar',
        description: null,
        fieldType: 'FILE',
        fieldTypeAttributes: {
          format: 'IMAGE',
          maxSize: null,
          typeRestrictions: null,
          __typename: 'FileFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68218033b337fc09bbf3',
        name: 'broker',
        displayName: 'Broker',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'user',
          refFieldDisplayName: 'User',
          relationTableName: 'u220njo',
          relationFieldName: 'bid',
          refTable: {
            id: '5c3c68128033b37c2909b643',
            name: 'Brokers',
            __typename: 'Table',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c68248033b393ed09bd11',
        name: 'customer',
        displayName: 'Customer',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'user',
          refFieldDisplayName: 'User',
          relationTableName: '4u40njg',
          relationFieldName: 'bid',
          refTable: {
            id: '5c3c68138033b334e109b6c1',
            name: 'Customers',
            __typename: 'Table',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
    ],
    __typename: 'Table',
  },
  {
    id: '5c3c67a95ec82c7dfd5b2c1d',
    name: 'Files',
    displayName: 'Files',
    isSystem: true,
    fields: [
      {
        id: '5c3c67a95ec82c47b85b2c1e',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67a95ec82ce4445b2c1f',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67a95ec82c05425b2c21',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67a95ec82c17465b2c25',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5c3c67a95ec82cdea85b2bff',
            name: 'Users',
            __typename: 'Table',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cf0665b2c27',
        name: 'fileId',
        displayName: 'File ID',
        description: null,
        fieldType: 'UUID',
        fieldTypeAttributes: {
          __typename: 'UUIDFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c481d5b2c29',
        name: 'downloadUrl',
        displayName: 'Download Url',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 191,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c16635b2c2b',
        name: 'shareUrl',
        displayName: 'Share Url',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 191,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c04315b2c2d',
        name: 'provider',
        displayName: 'Provider',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 191,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c50b55b2c2f',
        name: 'public',
        displayName: 'Public',
        description: null,
        fieldType: 'SWITCH',
        fieldTypeAttributes: {
          format: 'TRUE_FALSE',
          listOptions: null,
          __typename: 'SwitchFieldTypeAttributes',
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: 'false',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c03545b2c31',
        name: 'uploaded',
        displayName: 'Uploaded',
        description: null,
        fieldType: 'SWITCH',
        fieldTypeAttributes: {
          format: 'TRUE_FALSE',
          listOptions: null,
          __typename: 'SwitchFieldTypeAttributes',
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: 'false',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c20ce5b2c33',
        name: 'filename',
        displayName: 'File Name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 256,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c17435b2c35',
        name: 'uploadUrl',
        displayName: 'Upload Url',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 1024,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c7d175b2c37',
        name: 'fields',
        displayName: 'Fields',
        description: null,
        fieldType: 'JSON',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c47c15b2c38',
        name: 'meta',
        displayName: 'Meta',
        description: null,
        fieldType: 'JSON',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c21395b2c39',
        name: 'mods',
        displayName: 'Mods',
        description: null,
        fieldType: 'JSON',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c99a55b2c5e',
        name: 'Settings_menuBarLogo',
        displayName: 'Settings_menuBarLogo',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: {
          refFieldName: 'menuBarLogo',
          refFieldDisplayName: 'Menu Bar Logo',
          relationTableName: 'FileMenuBarLogo',
          relationFieldName: 'bid',
          refTable: {
            id: '5c3c67aa5ec82c60465b2c3a',
            name: 'Settings',
            __typename: 'Table',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cb6a65b2c64',
        name: 'Settings_landingPageImage',
        displayName: 'Settings_landingPageImage',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: {
          refFieldName: 'landingPageImage',
          refFieldDisplayName: 'Landing Page Image',
          relationTableName: 'FileLandingPageImage',
          relationFieldName: 'bid',
          refTable: {
            id: '5c3c67aa5ec82c60465b2c3a',
            name: 'Settings',
            __typename: 'Table',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cbc345b2ce7',
        name: 'Users_avatar',
        displayName: 'Users_avatar',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: {
          refFieldName: 'avatar',
          refFieldDisplayName: 'Avatar',
          relationTableName: 'FileAvatar',
          relationFieldName: 'bid',
          refTable: {
            id: '5c3c67a95ec82cdea85b2bff',
            name: 'Users',
            __typename: 'Table',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c68168033b33ede09b847',
        name: 'Properties_pictures',
        displayName: 'Properties_pictures',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'pictures',
          refFieldDisplayName: 'Pictures',
          relationTableName: 'bi00nqd',
          relationFieldName: 'bid',
          refTable: {
            id: '5c3c68118033b3450409b5c9',
            name: 'Properties',
            __typename: 'Table',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c68278033b3168009bece',
        name: 'Listings_documents',
        displayName: 'Listings_documents',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'documents',
          refFieldDisplayName: 'Documents',
          relationTableName: 'lx70n91',
          relationFieldName: 'bid',
          refTable: {
            id: '5c3c68148033b317e309b743',
            name: 'Listings',
            __typename: 'Table',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
    ],
    __typename: 'Table',
  },
  {
    id: '5c3c67aa5ec82c60465b2c3a',
    name: 'Settings',
    displayName: 'Settings',
    isSystem: true,
    fields: [
      {
        id: '5c3c67aa5ec82c302e5b2c3c',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c25635b2c3e',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c463f5b2c42',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5c3c67a95ec82cdea85b2bff',
            name: 'Users',
            __typename: 'Table',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c3a4d5b2c44',
        name: 'passwordMinLength',
        displayName: 'Password Min Length',
        description: null,
        fieldType: 'NUMBER',
        fieldTypeAttributes: {
          format: 'NUMBER',
          precision: 0,
          currency: null,
          minValue: null,
          maxValue: null,
          __typename: 'NumberFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: '8',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c3d475b2c46',
        name: 'passwordRequireNumbers',
        displayName: 'Password Require Numbers',
        description: null,
        fieldType: 'SWITCH',
        fieldTypeAttributes: {
          format: 'TRUE_FALSE',
          listOptions: null,
          __typename: 'SwitchFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: 'true',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c6c475b2c48',
        name: 'passwordRequireSpecial',
        displayName: 'Password Require Special Symbols',
        description: null,
        fieldType: 'SWITCH',
        fieldTypeAttributes: {
          format: 'TRUE_FALSE',
          listOptions: null,
          __typename: 'SwitchFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: 'false',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c21435b2c4a',
        name: 'passwordRequireUppercase',
        displayName: 'Password Require Uppercase Symbols',
        description: null,
        fieldType: 'SWITCH',
        fieldTypeAttributes: {
          format: 'TRUE_FALSE',
          listOptions: null,
          __typename: 'SwitchFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: 'true',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c4a845b2c4c',
        name: 'passwordRequireLowercase',
        displayName: 'Password Require Lowercase Symbols',
        description: null,
        fieldType: 'SWITCH',
        fieldTypeAttributes: {
          format: 'TRUE_FALSE',
          listOptions: null,
          __typename: 'SwitchFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: 'true',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c866d5b2c4e',
        name: 'passwordUpdateInterval',
        displayName: 'Password Update Interval',
        description: null,
        fieldType: 'NUMBER',
        fieldTypeAttributes: {
          format: 'NUMBER',
          precision: 0,
          currency: null,
          minValue: null,
          maxValue: null,
          __typename: 'NumberFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: '0',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c6e065b2c50',
        name: 'rememberDevice',
        displayName: 'Remember Device',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: 'always',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c36fa5b2c52',
        name: 'language',
        displayName: 'Language',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: 'en',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c26a75b2c54',
        name: 'dateFormat',
        displayName: 'Date Format',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: 'MM-DD-YYYY',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c3cb65b2c56',
        name: 'currency',
        displayName: 'Currency',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: 'usd',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c76ba5b2c58',
        name: 'timezone',
        displayName: 'Timezone',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: 'America/New_York',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82ce00f5b2c5a',
        name: 'menuBarLogo',
        displayName: 'Menu Bar Logo',
        description: null,
        fieldType: 'FILE',
        fieldTypeAttributes: {
          format: 'IMAGE',
          maxSize: null,
          typeRestrictions: null,
          __typename: 'FileFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c9b475b2c60',
        name: 'landingPageImage',
        displayName: 'Landing Page Image',
        description: null,
        fieldType: 'FILE',
        fieldTypeAttributes: {
          format: 'IMAGE',
          maxSize: null,
          typeRestrictions: null,
          __typename: 'FileFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82ce5495b2c66',
        name: 'vanityUrl',
        displayName: 'Vanity Url',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c67455b2c68',
        name: 'buttonLinkColor',
        displayName: 'Button Link Color',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: '#107AFE',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c115f5b2c6a',
        name: 'userInterfaceStyle',
        displayName: 'User Interface Style',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: 'light',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c7c0a5b2c6c',
        name: 'menuBarBGColor',
        displayName: 'Menu Bar Background Color',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: '#323C47',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c4aac5b2c6e',
        name: 'menuBarIconsColor',
        displayName: 'Menu Bar Icons Color',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: '#D3DCE6',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cafbc5b2c70',
        name: 'bgColor',
        displayName: 'Background Color',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: '#F4F5F6',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c9d4e5b2c72',
        name: 'containerColor',
        displayName: 'Container Color',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: '#FFFFFF',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c5a705b2c74',
        name: 'leftNavColor',
        displayName: 'Left Navigation Color',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: '#939EA7',
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
    ],
    __typename: 'Table',
  },
  {
    id: '5c3c67aa5ec82c2df45b2c76',
    name: 'Roles',
    displayName: 'Roles',
    isSystem: true,
    fields: [
      {
        id: '5c3c67aa5ec82ccf635b2c77',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c1a4e5b2c78',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cd28f5b2c7a',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c0e525b2c7e',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5c3c67a95ec82cdea85b2bff',
            name: 'Users',
            __typename: 'Table',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cbf565b2c80',
        name: 'name',
        displayName: 'Name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 191,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cf1f95b2c82',
        name: 'description',
        displayName: 'Description',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 1024,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c28685b2cd1',
        name: 'invitations',
        displayName: 'Invitations',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: {
          refFieldName: 'roles',
          refFieldDisplayName: 'Roles',
          relationTableName: 'InvitationRoles',
          relationFieldName: 'bid',
          refTable: {
            id: '5c3c67aa5ec82cdc315b2c88',
            name: 'Invitations',
            __typename: 'Table',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c4bae5b2cd9',
        name: 'users',
        displayName: 'User',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: {
          refFieldName: 'roles',
          refFieldDisplayName: 'Roles',
          relationTableName: 'UsersRoles',
          relationFieldName: 'bid',
          refTable: {
            id: '5c3c67a95ec82cdea85b2bff',
            name: 'Users',
            __typename: 'Table',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c81655b2cdb',
        name: 'permissions',
        displayName: 'Permissions',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: {
          refFieldName: 'role',
          refFieldDisplayName: 'Role',
          relationTableName: 'RolePermissions',
          relationFieldName: 'aid',
          refTable: {
            id: '5c3c67aa5ec82c07365b2ca0',
            name: 'Permissions',
            __typename: 'Table',
          },
          refFieldIsList: false,
          refFieldIsRequired: true,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c420e5b2cdf',
        name: 'apiTokens',
        displayName: 'API Tokens',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: {
          refFieldName: 'roles',
          refFieldDisplayName: 'Roles',
          relationTableName: 'RoleApiTokens',
          relationFieldName: 'aid',
          refTable: {
            id: '5c3c67aa5ec82c808d5b2cb3',
            name: 'ApiTokens',
            __typename: 'Table',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
    ],
    __typename: 'Table',
  },
  {
    id: '5c3c67aa5ec82cdc315b2c88',
    name: 'Invitations',
    displayName: 'Invitations',
    isSystem: true,
    fields: [
      {
        id: '5c3c67aa5ec82cd0a75b2c89',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c24e65b2c8a',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c32aa5b2c8c',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c56675b2c90',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5c3c67a95ec82cdea85b2bff',
            name: 'Users',
            __typename: 'Table',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c96855b2c92',
        name: 'uuid',
        displayName: 'UUID',
        description: null,
        fieldType: 'UUID',
        fieldTypeAttributes: {
          __typename: 'UUIDFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82ccc875b2c94',
        name: 'email',
        displayName: 'Email',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 191,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cc9515b2c96',
        name: 'firstName',
        displayName: 'First Name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c16db5b2c98',
        name: 'lastName',
        displayName: 'Last Name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 255,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c50d95b2c9a',
        name: 'resentOn',
        displayName: 'Resent On',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c785e5b2c9c',
        name: 'accepted',
        displayName: 'Accepted',
        description: null,
        fieldType: 'SWITCH',
        fieldTypeAttributes: {
          format: 'TRUE_FALSE',
          listOptions: null,
          __typename: 'SwitchFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82ccd965b2c9e',
        name: 'acceptedOn',
        displayName: 'Accepted On',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c0e245b2ccf',
        name: 'roles',
        displayName: 'Roles',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: {
          refFieldName: 'invitations',
          refFieldDisplayName: 'Invitations',
          relationTableName: 'InvitationRoles',
          relationFieldName: 'aid',
          refTable: {
            id: '5c3c67aa5ec82c2df45b2c76',
            name: 'Roles',
            __typename: 'Table',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cbb355b2cd3',
        name: 'invitedBy',
        displayName: 'Invited By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: {
          refFieldName: 'sentInvitations',
          refFieldDisplayName: 'Sent Invitations',
          relationTableName: 'InvitationInvitedBy',
          relationFieldName: 'aid',
          refTable: {
            id: '5c3c67a95ec82cdea85b2bff',
            name: 'Users',
            __typename: 'Table',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
    ],
    __typename: 'Table',
  },
  {
    id: '5c3c67aa5ec82c07365b2ca0',
    name: 'Permissions',
    displayName: 'Permissions',
    isSystem: true,
    fields: [
      {
        id: '5c3c67aa5ec82c2f785b2ca2',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cbfdf5b2ca4',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cc9775b2ca8',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5c3c67a95ec82cdea85b2bff',
            name: 'Users',
            __typename: 'Table',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c85ae5b2caa',
        name: 'appId',
        displayName: 'App Id',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 191,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cec975b2cac',
        name: 'resourceType',
        displayName: 'resourceType',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 191,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c5f1f5b2cae',
        name: 'resource',
        displayName: 'Resource',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 191,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cd7225b2cb2',
        name: 'permission',
        displayName: 'Permission',
        description: null,
        fieldType: 'JSON',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c4b0c5b2cdd',
        name: 'role',
        displayName: 'Role',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: null,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: {
          refFieldName: 'permissions',
          refFieldDisplayName: 'Permissions',
          relationTableName: 'RolePermissions',
          relationFieldName: 'bid',
          refTable: {
            id: '5c3c67aa5ec82c2df45b2c76',
            name: 'Roles',
            __typename: 'Table',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
    ],
    __typename: 'Table',
  },
  {
    id: '5c3c67aa5ec82c808d5b2cb3',
    name: 'ApiTokens',
    displayName: 'API tokens',
    isSystem: true,
    fields: [
      {
        id: '5c3c67aa5ec82c4c115b2cb4',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c6a6a5b2cb5',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cebf75b2cb7',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cf5d25b2cbb',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5c3c67a95ec82cdea85b2bff',
            name: 'Users',
            __typename: 'Table',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c5d705b2cbd',
        name: 'name',
        displayName: 'Name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 191,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82cb7df5b2ce1',
        name: 'roles',
        displayName: 'Roles',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: {
          refFieldName: 'apiTokens',
          refFieldDisplayName: 'API Tokens',
          relationTableName: 'RoleApiTokens',
          relationFieldName: 'bid',
          refTable: {
            id: '5c3c67aa5ec82c2df45b2c76',
            name: 'Roles',
            __typename: 'Table',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
    ],
    __typename: 'Table',
  },
  {
    id: '5c3c67aa5ec82c5b885b2cc1',
    name: 'EnvironmentVariables',
    displayName: 'Env variables',
    isSystem: true,
    fields: [
      {
        id: '5c3c67aa5ec82c68d25b2cc2',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c573e5b2cc3',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c5da45b2cc5',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c4e6b5b2cc9',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5c3c67a95ec82cdea85b2bff',
            name: 'Users',
            __typename: 'Table',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c12c65b2ccb',
        name: 'name',
        displayName: 'Name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 191,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c67aa5ec82c66085b2ccd',
        name: 'value',
        displayName: 'Value',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 10000,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
    ],
    __typename: 'Table',
  },
  {
    id: '5c3c68118033b3450409b5c9',
    name: 'Properties',
    displayName: 'Properties',
    isSystem: false,
    fields: [
      {
        id: '5c3c68118033b3518b09b5ca',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68118033b3990809b5cb',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68118033b3831d09b5cd',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68118033b37ee409b5d1',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5c3c67a95ec82cdea85b2bff',
            name: 'Users',
            __typename: 'Table',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c68168033b3126409b844',
        name: 'pictures',
        displayName: 'Pictures',
        description: null,
        fieldType: 'FILE',
        fieldTypeAttributes: {
          format: 'IMAGE',
          maxSize: null,
          typeRestrictions: null,
          __typename: 'FileFieldTypeAttributes',
        },
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68168033b3576009b8c8',
        name: 'bedrooms',
        displayName: 'Bedrooms',
        description: null,
        fieldType: 'NUMBER',
        fieldTypeAttributes: {
          format: 'NUMBER',
          precision: 0,
          currency: null,
          minValue: 0,
          maxValue: null,
          __typename: 'NumberFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68183aa063ce475ad6ec',
        name: 'title',
        displayName: 'title',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 500,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68198033b34c1309b94b',
        name: 'description',
        displayName: 'Description',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 500,
          __typename: 'TextFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c681b3aa06306485ad770',
        name: 'sqFootage',
        displayName: 'Sq Footage',
        description: null,
        fieldType: 'NUMBER',
        fieldTypeAttributes: {
          format: 'NUMBER',
          precision: 0,
          currency: null,
          minValue: 0,
          maxValue: null,
          __typename: 'NumberFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c681c8033b3bad809b9d0',
        name: 'bathrooms',
        displayName: 'Bathrooms',
        description: null,
        fieldType: 'NUMBER',
        fieldTypeAttributes: {
          format: 'NUMBER',
          precision: 0,
          currency: null,
          minValue: 0,
          maxValue: null,
          __typename: 'NumberFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c681d8033b3b39d09ba56',
        name: 'garage',
        displayName: 'Garage',
        description: null,
        fieldType: 'SWITCH',
        fieldTypeAttributes: {
          format: 'YES_NO',
          listOptions: null,
          __typename: 'SwitchFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: null,
        defaultValue: 'false',
        isSystem: false,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c681f8033b373e009badd',
        name: 'pool',
        displayName: 'Pool',
        description: null,
        fieldType: 'SWITCH',
        fieldTypeAttributes: {
          format: 'YES_NO',
          listOptions: null,
          __typename: 'SwitchFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: null,
        defaultValue: 'false',
        isSystem: false,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68208033b33d5609bb65',
        name: 'listings',
        displayName: 'Listings',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'property',
          refFieldDisplayName: 'Property',
          relationTableName: '0j10nsz',
          relationFieldName: 'aid',
          refTable: {
            id: '5c3c68148033b317e309b743',
            name: 'Listings',
            __typename: 'Table',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
    ],
    __typename: 'Table',
  },
  {
    id: '5c3c68128033b37c2909b643',
    name: 'Brokers',
    displayName: 'Brokers',
    isSystem: false,
    fields: [
      {
        id: '5c3c68128033b35aa909b644',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68128033b336fc09b645',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68128033b304ca09b647',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68128033b34d5509b64b',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5c3c67a95ec82cdea85b2bff',
            name: 'Users',
            __typename: 'Table',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c68218033b3216a09bbf1',
        name: 'user',
        displayName: 'User',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'broker',
          refFieldDisplayName: 'Broker',
          relationTableName: 'u220njo',
          relationFieldName: 'aid',
          refTable: {
            id: '5c3c67a95ec82cdea85b2bff',
            name: 'Users',
            __typename: 'Table',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c68238033b3437509bc7f',
        name: 'listings',
        displayName: 'Listings',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'broker',
          refFieldDisplayName: 'Broker',
          relationTableName: 'cl30n2e',
          relationFieldName: 'aid',
          refTable: {
            id: '5c3c68148033b317e309b743',
            name: 'Listings',
            __typename: 'Table',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
    ],
    __typename: 'Table',
  },
  {
    id: '5c3c68138033b334e109b6c1',
    name: 'Customers',
    displayName: 'Customers',
    isSystem: false,
    fields: [
      {
        id: '5c3c68138033b3575209b6c2',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68138033b3dadb09b6c3',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68138033b3614909b6c5',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68138033b3148b09b6c9',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5c3c67a95ec82cdea85b2bff',
            name: 'Users',
            __typename: 'Table',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c68248033b35e2809bd0f',
        name: 'user',
        displayName: 'User',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'customer',
          refFieldDisplayName: 'Customer',
          relationTableName: '4u40njg',
          relationFieldName: 'aid',
          refTable: {
            id: '5c3c67a95ec82cdea85b2bff',
            name: 'Users',
            __typename: 'Table',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c68258033b3b37e09bda1',
        name: 'purchases',
        displayName: 'Purchases',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'buyer',
          refFieldDisplayName: 'Buyer',
          relationTableName: 'zz50n9k',
          relationFieldName: 'aid',
          refTable: {
            id: '5c3c68148033b317e309b743',
            name: 'Listings',
            __typename: 'Table',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c68268033b3f61609be35',
        name: 'sales',
        displayName: 'Sales',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'seller',
          refFieldDisplayName: 'Seller',
          relationTableName: 'v460niu',
          relationFieldName: 'aid',
          refTable: {
            id: '5c3c68148033b317e309b743',
            name: 'Listings',
            __typename: 'Table',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
    ],
    __typename: 'Table',
  },
  {
    id: '5c3c68148033b317e309b743',
    name: 'Listings',
    displayName: 'Listings',
    isSystem: false,
    fields: [
      {
        id: '5c3c68148033b31c5109b744',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68148033b3839a09b745',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68148033b3c6b309b747',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68148033b3ab8a09b74b',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5c3c67a95ec82cdea85b2bff',
            name: 'Users',
            __typename: 'Table',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c68208033b3c78f09bb67',
        name: 'property',
        displayName: 'Property',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'listings',
          refFieldDisplayName: 'Listings',
          relationTableName: '0j10nsz',
          relationFieldName: 'bid',
          refTable: {
            id: '5c3c68118033b3450409b5c9',
            name: 'Properties',
            __typename: 'Table',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c68238033b30dcc09bc81',
        name: 'broker',
        displayName: 'Broker',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'listings',
          refFieldDisplayName: 'Listings',
          relationTableName: 'cl30n2e',
          relationFieldName: 'bid',
          refTable: {
            id: '5c3c68128033b37c2909b643',
            name: 'Brokers',
            __typename: 'Table',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c68258033b384e609bda3',
        name: 'buyer',
        displayName: 'Buyer',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'purchases',
          refFieldDisplayName: 'Purchases',
          relationTableName: 'zz50n9k',
          relationFieldName: 'bid',
          refTable: {
            id: '5c3c68138033b334e109b6c1',
            name: 'Customers',
            __typename: 'Table',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c68268033b3115209be37',
        name: 'seller',
        displayName: 'Seller',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'sales',
          refFieldDisplayName: 'Sales',
          relationTableName: 'v460niu',
          relationFieldName: 'bid',
          refTable: {
            id: '5c3c68138033b334e109b6c1',
            name: 'Customers',
            __typename: 'Table',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
          __typename: 'Relation',
        },
        __typename: 'TableField',
      },
      {
        id: '5c3c68278033b36cd409becb',
        name: 'documents',
        displayName: 'Documents',
        description: null,
        fieldType: 'FILE',
        fieldTypeAttributes: {
          format: 'FILE',
          maxSize: null,
          typeRestrictions: null,
          __typename: 'FileFieldTypeAttributes',
        },
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68288033b34b0f09bf65',
        name: 'status',
        displayName: 'Status',
        description: null,
        fieldType: 'SWITCH',
        fieldTypeAttributes: {
          format: 'CUSTOM',
          listOptions: [
            'Lead',
            'Closing',
            'Active',
            'Closed',
            'Cancelled',
          ],
          __typename: 'SwitchFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c68298033b3213f09bffd',
        name: 'closingDate',
        displayName: 'Closing Date',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATE',
          __typename: 'DateFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
      {
        id: '5c3c682a8033b32e1709c096',
        name: 'price',
        displayName: 'Price',
        description: null,
        fieldType: 'NUMBER',
        fieldTypeAttributes: {
          format: 'NUMBER',
          precision: 2,
          currency: null,
          minValue: 0,
          maxValue: null,
          __typename: 'NumberFieldTypeAttributes',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
        __typename: 'TableField',
      },
    ],
    __typename: 'Table',
  },
];

export {
  tablesSchema,
};

