export enum PACKAGES {
  API_CLIENT = '@8base/api-client',
  APOLLO_CLIENT = '@8base/apollo-client',
  APOLLO_LINKS = '@8base/apollo-links',
  APP_PROVIDER = '@8base/app-provider',
  REACT_AUTH = '@8base/react-auth',
  AUTH = '@8base/auth',
  CRUD = '@8base/crud',
  FILE_INPUT = '@8base/file-input',
  FORMS = '@8base/forms',
  PERMISSIONS_PROVIDER = '@8base/permissions-provider',
  TABLE_SCHEMA_PROVIDER = '@8base/table-schema-provider',
  UTILS = '@8base/utils',
  VALIDATE = '@8base/validate',
  API_TOKEN_AUTH_CLIENT = '@8base/api-token-auth-client',
  WEB_AUTH0_AUTH_CLIENT = '@8base/web-auth0-auth-client',
}
