export const TABLES = [
  {
    id: '5d0c8cf9bb69adb36438bbdc',
    name: 'Properties',
    displayName: 'Properties',
    isSystem: false,
    fields: [
      {
        id: '5d0c8cf9bb69ad251338bbdd',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d0c8cf9bb69ad1a7e38bbde',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d0c8cf9bb69adb7b938bbe1',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d0c8cf9bb69ad6c2338bbe7',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5d0c8cecbb69adf5f338b71a',
            name: 'Users',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
        },
      },
      {
        id: '5d0c8d0bbb69ada3d038bd80',
        name: 'name',
        displayName: 'Name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 100,
        },
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d0c8d80bb69adccf138c6ab',
        name: 'listings',
        displayName: 'Listings',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'property',
          refFieldDisplayName: 'Property',
          relationTableName: 'ListingsProperty',
          relationFieldName: 'propertyAId',
          refTable: {
            id: '5d0c8d1dbb69ad06c438be94',
            name: 'Listings',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
        },
      },
    ],
  },
  {
    id: '5d0c8d1dbb69ad06c438be94',
    name: 'Listings',
    displayName: 'Listings',
    isSystem: false,
    fields: [
      {
        id: '5d0c8d1dbb69adf2e438be95',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d0c8d1dbb69adf8b238be96',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d0c8d1dbb69adf75f38be99',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d0c8d1dbb69ad848138be9f',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5d0c8cecbb69adf5f338b71a',
            name: 'Users',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
        },
      },
      {
        id: '5d0c8d2cbb69adaf5238c047',
        name: 'name',
        displayName: 'Name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 100,
        },
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d0c8d62bb69ad0a2138c451',
        name: 'broker',
        displayName: 'Broker',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'listings',
          refFieldDisplayName: 'Listings',
          relationTableName: 'BrokerListings',
          relationFieldName: 'listingBId',
          refTable: {
            id: '5d0c8d44bb69ad21c838c165',
            name: 'Broker',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
        },
      },
      {
        id: '5d0c8d80bb69ad408b38c6ad',
        name: 'property',
        displayName: 'Property',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'listings',
          refFieldDisplayName: 'Listings',
          relationTableName: 'ListingsProperty',
          relationFieldName: 'listingBId',
          refTable: {
            id: '5d0c8cf9bb69adb36438bbdc',
            name: 'Properties',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
        },
      },
    ],
  },
  {
    id: '5d0c8d44bb69ad21c838c165',
    name: 'Broker',
    displayName: 'Broker',
    isSystem: false,
    fields: [
      {
        id: '5d0c8d44bb69adea0838c166',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d0c8d44bb69ade5f338c167',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d0c8d44bb69ad8f0738c16a',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d0c8d44bb69ad406538c170',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5d0c8cecbb69adf5f338b71a',
            name: 'Users',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
        },
      },
      {
        id: '5d0c8d57bb69adfc8538c327',
        name: 'name',
        displayName: 'Name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 100,
        },
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d0c8d62bb69ad930338c44f',
        name: 'listings',
        displayName: 'Listings',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'broker',
          refFieldDisplayName: 'Broker',
          relationTableName: 'BrokerListings',
          relationFieldName: 'brokerAId',
          refTable: {
            id: '5d0c8d1dbb69ad06c438be94',
            name: 'Listings',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
        },
      },
    ],
  },
];

export const DATA = {
  Properties: [
    {
      name: 'Property-01',
      listings: [
        {
          $id: 'cjx5svv1n002w01jp3rztfrzv',
        },
        {
          $id: 'cjx5svzs8003601jp1k1n7uue',
        },
        {
          $id: 'cjx5sw30s003401jv8ymd0lu7',
        },
      ],
      $id: 'cjx5swijs004301jphta2cf4u',
    },
  ],
  Listings: [
    {
      name: 'Listing-01',
      broker: {
        $id: 'cjx5swrpk004q01jp987l9i7b',
      },
      property: {
        $id: 'cjx5swijs004301jphta2cf4u',
      },
      $id: 'cjx5svv1n002w01jp3rztfrzv',
    },
    {
      name: 'Listing-02',
      broker: {
        $id: 'cjx5swrpk004q01jp987l9i7b',
      },
      property: {
        $id: 'cjx5swijs004301jphta2cf4u',
      },
      $id: 'cjx5svzs8003601jp1k1n7uue',
    },
    {
      name: 'Listing-03',
      broker: {
        $id: 'cjx5swrpk004q01jp987l9i7b',
      },
      property: {
        $id: 'cjx5swijs004301jphta2cf4u',
      },
      $id: 'cjx5sw30s003401jv8ymd0lu7',
    },
  ],
  Broker: [
    {
      name: 'Broker-01',
      listings: [
        {
          $id: 'cjx5svv1n002w01jp3rztfrzv',
        },
        {
          $id: 'cjx5svzs8003601jp1k1n7uue',
        },
        {
          $id: 'cjx5sw30s003401jv8ymd0lu7',
        },
      ],
      $id: 'cjx5swrpk004q01jp987l9i7b',
    },
  ],
  Files: [],
};

export const WORKSPACE_WITH_RELATIONS_2 = {
  tables: TABLES,
  data: DATA,
};
