export const TABLES = [
  {
    id: '5d075ba8e9e478d1ce74f804',
    name: 'First',
    displayName: 'First',
    isSystem: false,
    fields: [
      {
        id: '5d075ba8e9e478848274f805',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d075ba8e9e4787dca74f806',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d075ba8e9e4785bee74f809',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d075ba8e9e478df7c74f80f',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5d075b9fe9e4785c1e74f4ec',
            name: 'Users',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
        },
      },
      {
        id: '5d075bb5e9e478462574f9a8',
        name: 'name',
        displayName: 'Name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 100,
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d075bc4e9e478781f74fabc',
        name: 'date',
        displayName: 'Date',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATE',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d075bdde9e4786c4474fbd2',
        name: 'isRed',
        displayName: 'Is Red',
        description: null,
        fieldType: 'SWITCH',
        fieldTypeAttributes: {
          format: 'TRUE_FALSE',
          listOptions: null,
        },
        isList: false,
        isRequired: false,
        isUnique: null,
        defaultValue: 'false',
        isSystem: false,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d075bf599d6f2b774cc8bb8',
        name: 'values',
        displayName: 'Values',
        description: null,
        fieldType: 'NUMBER',
        fieldTypeAttributes: {
          format: 'NUMBER',
          precision: 0,
          currency: null,
          minValue: null,
          maxValue: null,
          isBigInt: null,
        },
        isList: true,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
      },
    ],
  },
  {
    id: '5d075bfa99d6f2178bcc8cd2',
    name: 'Second',
    displayName: 'Second',
    isSystem: false,
    fields: [
      {
        id: '5d075bfa99d6f26165cc8cd3',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d075bfa99d6f2c60fcc8cd4',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d075bfa99d6f27ddecc8cd7',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d075bfa99d6f21509cc8cdd',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5d075b9fe9e4785c1e74f4ec',
            name: 'Users',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
        },
      },
      {
        id: '5d075c0d99d6f2dc26cc8e8e',
        name: 'name',
        displayName: 'Name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 100,
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d075c1599d6f248f0cc8fb2',
        name: 'date',
        displayName: 'Date',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATE',
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d075c3a99d6f28265cc90d8',
        name: 'switch',
        displayName: 'Switch',
        description: null,
        fieldType: 'SWITCH',
        fieldTypeAttributes: {
          format: 'ON_OFF',
          listOptions: null,
        },
        isList: false,
        isRequired: true,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
      },
    ],
  },
];

export const DATA = {
  First: [
    {
      createdAt: '2019-06-17T09:26:10.375Z',
      updatedAt: '2019-06-17T09:26:10.375Z',
      createdBy: {
        $id: 'cjx0665o700bp01la6811f2pr',
      },
      name: 'First',
      date: '2019-06-01',
      isRed: true,
      values: [1, 2, 3],
      $id: 'cjx06bydi00g301l73iuydrpi',
    },
    {
      createdAt: '2019-06-17T09:26:10.406Z',
      updatedAt: '2019-06-17T09:26:10.406Z',
      createdBy: {
        $id: 'cjx0665o700bp01la6811f2pr',
      },
      name: 'First',
      date: null,
      isRed: false,
      values: null,
      $id: 'cjx06byee00g401l7bbv09bq5',
    },
  ],
  Second: [
    {
      createdAt: '2019-06-17T09:26:38.965Z',
      updatedAt: '2019-06-17T09:26:38.965Z',
      createdBy: {
        $id: 'cjx0665o700bp01la6811f2pr',
      },
      name: 'Second',
      date: '2019-06-01',
      switch: true,
      $id: 'cjx06ckfo00gd01l72ggbhj7z',
    },
  ],
};

export const WORKSPACE_WITHOUT_RELATIONS = {
  tables: TABLES,
  data: DATA,
};
