import path from 'path';

const currentWorkingDir = path.resolve(__dirname);

export const TABLES = [
  {
    id: '5d076bde99d6f24b06cccd86',
    name: 'First',
    displayName: 'First',
    isSystem: false,
    fields: [
      {
        id: '5d076bde99d6f2be52cccd87',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d076bde99d6f280d4cccd88',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d076bde99d6f29b32cccd8b',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d076bde99d6f28f08cccd91',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5d076bd699d6f25740ccca6e',
            name: 'Users',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
        },
      },
      {
        id: '5d076bf499d6f26417cccf2a',
        name: 'avatar',
        displayName: 'Avatar',
        description: null,
        fieldType: 'FILE',
        fieldTypeAttributes: {
          format: 'FILE',
          maxSize: null,
          typeRestrictions: null,
        },
        isList: false,
        isRequired: true,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d076bff99d6f23b34ccd139',
        name: 'pictures',
        displayName: 'Pictures',
        description: null,
        fieldType: 'FILE',
        fieldTypeAttributes: {
          format: 'FILE',
          maxSize: null,
          typeRestrictions: null,
        },
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
      },
    ],
  },
  {
    id: '5d076bd699d6f2302dccca9a',
    name: 'Files',
    displayName: 'Files',
    isSystem: true,
    fields: [
      {
        id: '5d076bd699d6f2562fccca9b',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d076bd699d6f27b04ccca9c',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d076bd699d6f26776ccca9f',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d076bd699d6f20a78cccaa5',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5d076bd699d6f25740ccca6e',
            name: 'Users',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
        },
      },
      {
        id: '5d076bd699d6f23374cccaa7',
        name: 'fileId',
        displayName: 'File ID',
        description: null,
        fieldType: 'UUID',
        fieldTypeAttributes: {},
        isList: false,
        isRequired: false,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d076bd699d6f2707ecccaa9',
        name: 'downloadUrl',
        displayName: 'Download Url',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 191,
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d076bd699d6f24134cccaac',
        name: 'shareUrl',
        displayName: 'Share Url',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 191,
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d076bd699d6f22690cccaaf',
        name: 'provider',
        displayName: 'Provider',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 191,
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d076bd699d6f25fafcccab2',
        name: 'public',
        displayName: 'Public',
        description: null,
        fieldType: 'SWITCH',
        fieldTypeAttributes: {
          format: 'TRUE_FALSE',
          listOptions: null,
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: 'false',
        isSystem: true,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d076bd699d6f21724cccab5',
        name: 'uploaded',
        displayName: 'Uploaded',
        description: null,
        fieldType: 'SWITCH',
        fieldTypeAttributes: {
          format: 'TRUE_FALSE',
          listOptions: null,
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: 'false',
        isSystem: true,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d076bd699d6f25ed4cccab8',
        name: 'filename',
        displayName: 'File Name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 256,
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d076bd699d6f26724cccabb',
        name: 'uploadUrl',
        displayName: 'Upload Url',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 1024,
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d076bd699d6f253d0cccabe',
        name: 'fields',
        displayName: 'Fields',
        description: null,
        fieldType: 'JSON',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d076bd699d6f26b93cccabf',
        name: 'meta',
        displayName: 'Meta',
        description: null,
        fieldType: 'JSON',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d076bd799d6f281a7cccac0',
        name: 'mods',
        displayName: 'Mods',
        description: null,
        fieldType: 'JSON',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d076bd799d6f259e1cccaf3',
        name: 'settings_menuBarLogo',
        displayName: 'settings_menuBarLogo',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: {
          refFieldName: 'menuBarLogo',
          refFieldDisplayName: 'Menu Bar Logo',
          relationTableName: 'FileMenuBarLogo',
          relationFieldName: 'fileBId',
          refTable: {
            id: '5d076bd799d6f2725fcccac1',
            name: 'Settings',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
        },
      },
      {
        id: '5d076bd799d6f239fecccaf9',
        name: 'settings_landingPageImage',
        displayName: 'settings_landingPageImage',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: {
          refFieldName: 'landingPageImage',
          refFieldDisplayName: 'Landing Page Image',
          relationTableName: 'FileLandingPageImage',
          relationFieldName: 'fileBId',
          refTable: {
            id: '5d076bd799d6f2725fcccac1',
            name: 'Settings',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
        },
      },
      {
        id: '5d076bd799d6f2fb2fcccb91',
        name: 'users_avatar',
        displayName: 'users_avatar',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: true,
        isMeta: false,
        relation: {
          refFieldName: 'avatar',
          refFieldDisplayName: 'Avatar',
          relationTableName: 'FileAvatar',
          relationFieldName: 'fileBId',
          refTable: {
            id: '5d076bd699d6f25740ccca6e',
            name: 'Users',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
        },
      },
      {
        id: '5d076bf499d6f27b37cccf2d',
        name: 'first_avatar',
        displayName: 'first_avatar',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'avatar',
          refFieldDisplayName: 'Avatar',
          relationTableName: 'FileFirsts',
          relationFieldName: 'fileBId',
          refTable: {
            id: '5d076bde99d6f24b06cccd86',
            name: 'First',
          },
          refFieldIsList: false,
          refFieldIsRequired: true,
        },
      },
      {
        id: '5d076bff99d6f25c00ccd13c',
        name: 'first_pictures',
        displayName: 'first_pictures',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'pictures',
          refFieldDisplayName: 'Pictures',
          relationTableName: 'FilesFirsts',
          relationFieldName: 'fileBId',
          refTable: {
            id: '5d076bde99d6f24b06cccd86',
            name: 'First',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
        },
      },
    ],
  },
];

export const DATA = {
  First: [
    {
      createdAt: '2019-06-17T10:32:26.203Z',
      updatedAt: '2019-06-17T10:32:26.203Z',
      createdBy: {
        $id: 'cjx08n4nt00ll01l75zdedg4y',
      },
      avatar: {
        $id: 'cjx08p6e500n601l78qkc968c',
      },
      pictures: [
        {
          $id: 'cjx08p6l400n701l7btv4d0ui',
        },
        {
          $id: 'cjx08p6v300n801l7bdo98otx',
        },
        {
          $id: 'cjx08p70l00n901l731lpcu2c',
        },
      ],
      $id: 'cjx08p65700n501l72lc4b36k',
    },
  ],
  Files: [
    {
      public: true,
      filename: 'image-1',
      meta: {
        path: 'production/cjx08n1c400lg01l79jsa4wlp/cjx08o0ji00mr01l73krngler/lkPrm0N4QFiEAF7aXs7Q_Test.jpg',
      },
      mods: null,
      $id: 'cjx08p6e500n601l78qkc968c',
      url: 'https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png',
    },
    {
      public: false,
      filename: 'image-1',
      meta: {
        path: 'production/cjx08n1c400lg01l79jsa4wlp/cjx08o0ji00mr01l73krngler/KQmDvFQMSiltE4dAYeXA_Test_pictures.jpg',
      },
      mods: null,
      $id: 'cjx08p6l400n701l7btv4d0ui',
      url: `${currentWorkingDir}/files/image-1`,
    },
    {
      public: false,
      filename: 'image-2',
      meta: {
        path: 'production/cjx08n1c400lg01l79jsa4wlp/cjx08o0ji00mr01l73krngler/3mnrbOLhSK6lk2TRAYXT_Test_pictures.jpg',
      },
      mods: null,
      $id: 'cjx08p6v300n801l7bdo98otx',
      url: `${currentWorkingDir}/files/image-2`,
    },
    {
      public: false,
      filename: 'image-3',
      meta: {
        path: 'production/cjx08n1c400lg01l79jsa4wlp/cjx08o0ji00mr01l73krngler/FR4VrclyS1GqCMPGicz6_Test_pictures.jpg',
      },
      mods: null,
      $id: 'cjx08p70l00n901l731lpcu2c',
      url: `${currentWorkingDir}/files/image-3`,
    },
  ],
};

export const WORKSPACE_WITH_FILES = {
  tables: TABLES,
  data: DATA,
};
