export const TABLES = [
  {
    id: '5cf8fca24beb4b79d5235b5a',
    name: 'First',
    displayName: 'First',
    isSystem: false,
    fields: [
      {
        id: '5cf8fca24beb4b252e235b5b',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5cf8fca24beb4b472d235b5c',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5cf8fca24beb4bd9fe235b5f',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5cf8fca24beb4b2c42235b65',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5cf8fc944beb4bb446235554',
            name: 'Users',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
        },
      },
      {
        id: '5cf8fcb14beb4b8817235f60',
        name: 'name',
        displayName: 'name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 100,
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
      },
      {
        id: '5cf8fcd24beb4b4b952365e5',
        name: 'second',
        displayName: 'Second',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'first',
          refFieldDisplayName: 'First',
          relationTableName: 'FirstSecond',
          relationFieldName: 'firstAId',
          refTable: {
            id: '5cf8fcb44beb4b5d95236076',
            name: 'Second',
          },
          refFieldIsList: false,
          refFieldIsRequired: true,
        },
      },
      {
        id: '5cf916ac4ca0f4daf4f05a01',
        name: 'fourth',
        displayName: 'Fourth',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'first',
          refFieldDisplayName: 'First',
          relationTableName: 'FirstFourth',
          relationFieldName: 'firstAId',
          refTable: {
            id: '5cf91649a287276c417df076',
            name: 'Fourth',
          },
          refFieldIsList: false,
          refFieldIsRequired: true,
        },
      },
      {
        id: '5d0259e7ec05d63db6db44cf',
        name: 'fifth',
        displayName: 'Fifth',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'firsts',
          refFieldDisplayName: 'Firsts',
          relationTableName: 'FifthFirsts',
          relationFieldName: 'firstBId',
          refTable: {
            id: '5d0216677ab1c4143f9d59f5',
            name: 'Fifth',
          },
          refFieldIsList: true,
          refFieldIsRequired: false,
        },
      },
    ],
  },
  {
    id: '5cf8fcb44beb4b5d95236076',
    name: 'Second',
    displayName: 'Second',
    isSystem: false,
    fields: [
      {
        id: '5cf8fcb44beb4b81b8236077',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5cf8fcb44beb4b0855236078',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5cf8fcb44beb4bdd1923607b',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5cf8fcb44beb4b18a9236081',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5cf8fc944beb4bb446235554',
            name: 'Users',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
        },
      },
      {
        id: '5cf8fcc34beb4b70a42364c3',
        name: 'name',
        displayName: 'name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 100,
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
      },
      {
        id: '5cf8fcd24beb4b061d2365e3',
        name: 'first',
        displayName: 'First',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'second',
          refFieldDisplayName: 'Second',
          relationTableName: 'FirstSecond',
          relationFieldName: 'secondBId',
          refTable: {
            id: '5cf8fca24beb4b79d5235b5a',
            name: 'First',
          },
          refFieldIsList: false,
          refFieldIsRequired: true,
        },
      },
      {
        id: '5cf90b7f4beb4babc4241319',
        name: 'third',
        displayName: 'Third',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'second',
          refFieldDisplayName: 'Second',
          relationTableName: 'SecondThird',
          relationFieldName: 'secondAId',
          refTable: {
            id: '5cf90b6569b93f858aa7a49d',
            name: 'Third',
          },
          refFieldIsList: false,
          refFieldIsRequired: true,
        },
      },
    ],
  },
  {
    id: '5cf90b6569b93f858aa7a49d',
    name: 'Third',
    displayName: 'Third',
    isSystem: false,
    fields: [
      {
        id: '5cf90b6569b93f05cfa7a49e',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5cf90b6569b93fc6eda7a49f',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5cf90b6569b93f764ba7a4a2',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5cf90b6569b93f5731a7a4a8',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5cf8fc944beb4bb446235554',
            name: 'Users',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
        },
      },
      {
        id: '5cf90b715005bfc29ca310cd',
        name: 'name',
        displayName: 'name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 100,
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
      },
      {
        id: '5cf90b7f4beb4b9d18241317',
        name: 'second',
        displayName: 'Second',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'third',
          refFieldDisplayName: 'Third',
          relationTableName: 'SecondThird',
          relationFieldName: 'thirdBId',
          refTable: {
            id: '5cf8fcb44beb4b5d95236076',
            name: 'Second',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
        },
      },
      {
        id: '5cf916724beb4b456524af23',
        name: 'fourth',
        displayName: 'Fourth',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'third',
          refFieldDisplayName: 'Third',
          relationTableName: 'FourthThird',
          relationFieldName: 'thirdAId',
          refTable: {
            id: '5cf91649a287276c417df076',
            name: 'Fourth',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
        },
      },
    ],
  },
  {
    id: '5cf91649a287276c417df076',
    name: 'Fourth',
    displayName: 'Fourth',
    isSystem: false,
    fields: [
      {
        id: '5cf91649a2872750be7df077',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5cf91649a287278f617df078',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5cf91649a28727c85c7df07b',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5cf91649a2872704577df081',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5cf8fc944beb4bb446235554',
            name: 'Users',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
        },
      },
      {
        id: '5cf9165c4beb4bc24124ade3',
        name: 'name',
        displayName: 'name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 100,
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
      },
      {
        id: '5cf916724beb4b70d724af25',
        name: 'third',
        displayName: 'Third',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'fourth',
          refFieldDisplayName: 'Fourth',
          relationTableName: 'FourthThird',
          relationFieldName: 'fourthBId',
          refTable: {
            id: '5cf90b6569b93f858aa7a49d',
            name: 'Third',
          },
          refFieldIsList: false,
          refFieldIsRequired: true,
        },
      },
      {
        id: '5cf916ac4ca0f41046f05a03',
        name: 'first',
        displayName: 'First',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'fourth',
          refFieldDisplayName: 'Fourth',
          relationTableName: 'FirstFourth',
          relationFieldName: 'fourthBId',
          refTable: {
            id: '5cf8fca24beb4b79d5235b5a',
            name: 'First',
          },
          refFieldIsList: false,
          refFieldIsRequired: true,
        },
      },
    ],
  },
  {
    id: '5d0216677ab1c4143f9d59f5',
    name: 'Fifth',
    displayName: 'Fifth',
    isSystem: false,
    fields: [
      {
        id: '5d0216677ab1c422529d59f6',
        name: 'id',
        displayName: 'ID',
        description: null,
        fieldType: 'ID',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: true,
        isUnique: true,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d0216677ab1c499b99d59f7',
        name: 'createdAt',
        displayName: 'Created At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d0216677ab1c42cc09d59fa',
        name: 'updatedAt',
        displayName: 'Updated At',
        description: null,
        fieldType: 'DATE',
        fieldTypeAttributes: {
          format: 'DATETIME',
        },
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: null,
      },
      {
        id: '5d0216677ab1c454499d5a00',
        name: 'createdBy',
        displayName: 'Created By',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: false,
        isRequired: false,
        isUnique: false,
        defaultValue: null,
        isSystem: true,
        isMeta: true,
        relation: {
          refFieldName: null,
          refFieldDisplayName: null,
          relationTableName: 'Users',
          relationFieldName: null,
          refTable: {
            id: '5cf8fc944beb4bb446235554',
            name: 'Users',
          },
          refFieldIsList: null,
          refFieldIsRequired: null,
        },
      },
      {
        id: '5d021672ace24974e928446c',
        name: 'name',
        displayName: 'name',
        description: null,
        fieldType: 'TEXT',
        fieldTypeAttributes: {
          format: 'UNFORMATTED',
          fieldSize: 100,
        },
        isList: false,
        isRequired: true,
        isUnique: false,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: null,
      },
      {
        id: '5d0259e7ec05d643dddb44cd',
        name: 'firsts',
        displayName: 'Firsts',
        description: null,
        fieldType: 'RELATION',
        fieldTypeAttributes: null,
        isList: true,
        isRequired: false,
        isUnique: null,
        defaultValue: null,
        isSystem: false,
        isMeta: false,
        relation: {
          refFieldName: 'fifth',
          refFieldDisplayName: 'Fifth',
          relationTableName: 'FifthFirsts',
          relationFieldName: 'fifthAId',
          refTable: {
            id: '5cf8fca24beb4b79d5235b5a',
            name: 'First',
          },
          refFieldIsList: false,
          refFieldIsRequired: false,
        },
      },
    ],
  },
];

export const DATA = {
  First: [
    {
      createdAt: '2019-06-12T09:54:46.477Z',
      updatedAt: '2019-06-12T09:54:46.477Z',
      createdBy: {
        $id: 'cjumd4yow000001rzn8unb0tf',
      },
      name: 'First',
      second: {
        $id: 'cjwt25h7h002m01mm4vi6fe2m',
      },
      fourth: {
        $id: 'cjwt25h9h002n01mm7gmy70se',
      },
      fifth: {
        $id: 'cjwuqwsud021201l4fxmydii7',
      },
      $id: 'cjwt25h71002l01mmdmnogau1',
    },
  ],
  Second: [
    {
      createdAt: '2019-06-12T09:54:46.493Z',
      updatedAt: '2019-06-12T09:54:46.493Z',
      createdBy: {
        $id: 'cjumd4yow000001rzn8unb0tf',
      },
      name: 'Second',
      first: {
        $id: 'cjwt25h71002l01mmdmnogau1',
      },
      third: {
        $id: 'cjwt28t48002b01lghwt51ej9',
      },
      $id: 'cjwt25h7h002m01mm4vi6fe2m',
    },
  ],
  Third: [
    {
      createdAt: '2019-06-12T09:57:21.897Z',
      updatedAt: '2019-06-12T09:57:21.897Z',
      createdBy: {
        $id: 'cjumd4yow000001rzn8unb0tf',
      },
      name: 'Third',
      second: {
        $id: 'cjwt25h7h002m01mm4vi6fe2m',
      },
      fourth: {
        $id: 'cjwt25h9h002n01mm7gmy70se',
      },
      $id: 'cjwt28t48002b01lghwt51ej9',
    },
  ],
  Fourth: [
    {
      createdAt: '2019-06-12T09:54:46.565Z',
      updatedAt: '2019-06-12T09:54:46.565Z',
      createdBy: {
        $id: 'cjumd4yow000001rzn8unb0tf',
      },
      name: 'Fourth',
      third: {
        $id: 'cjwt28t48002b01lghwt51ej9',
      },
      first: {
        $id: 'cjwt25h71002l01mmdmnogau1',
      },
      $id: 'cjwt25h9h002n01mm7gmy70se',
    },
  ],
  Fifth: [
    {
      createdAt: '2019-06-13T14:15:38.245Z',
      updatedAt: '2019-06-13T14:17:12.257Z',
      createdBy: {
        $id: 'cjumd4yow000001rzn8unb0tf',
      },
      name: 'Fifth',
      firsts: [
        {
          $id: 'cjwt25h71002l01mmdmnogau1',
        },
      ],
      $id: 'cjwuqwsud021201l4fxmydii7',
    },
  ],
};

export const WORKSPACE_WITH_RELATIONS = {
  tables: TABLES,
  data: DATA,
};
